# Generated by Django 3.0.2 on 2020-01-31 20:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('creado', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('publicacion', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 20, 56, 34, 28617, tzinfo=utc), verbose_name='Fecha publicacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categorias', models.ManyToManyField(to='blog.Categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-creado'],
            },
        ),
    ]
